### ISSUE TITLE
Help an error 

### ISSUE THREAD

**Issue by shahadS1l** [xzippyzachx/UnityFirebaseDatabaseTutorial#1]
<img width="1287" alt="Screen Shot 2021-01-28 at 1 22 37 AM" src="https://user-images.githubusercontent.com/78021126/106062149-732e1f80-6107-11eb-9330-d709682c57f8.png">

please can help when i was trying your code this error is shown ! 

also i wanna ask please i have a registration page it's contain name , email , pass and age how can i save them together in the firebase in one scene ?

please i will really appreciate your help 
thank you for your time

**Comment by shahadS1l** [comment]
<img width="1287" alt="Screen Shot 2021-01-28 at 1 22 37 AM" src="https://user-images.githubusercontent.com/78021126/106062496-e8015980-6107-11eb-9e3b-7efe19f28e45.png">

**Comment by shahadS1l** [comment]
<img width="1287" alt="Screen Shot 2021-01-28 at 1 26 50 AM" src="https://user-images.githubusercontent.com/78021126/106062531-f485b200-6107-11eb-8f11-90643d9a3b6d.png">

**Comment by xzippyzachx** [comment]
Hello,

Please join my discord server and ask for help in the help channel. Link to
join is in the description of all my videos.

Thanks,
zach
